[tool.poetry]
name = "dbt-simple"
version = "0.1.0"
description = "dbt simple 예제"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
dbt-core = ">=1.10.6,<2.0.0"
dbt-bigquery = "^1.10.1"
