default:
  target: "{{ env_var('DBT_TARGET') }}"
  outputs:
    local:
      type: postgres
      host: "{{ env_var('LOCAL_ANALYTICS_POSTGRES_HOST') }}"
      user: "{{ env_var('LOCAL_ANALYTICS_POSTGRES_USER') }}"
      password: "{{ env_var('LOCAL_ANALYTICS_POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('LOCAL_ANALYTICS_POSTGRES_DB') }}"
      schema: "{{ env_var('LOCAL_ANALYTICS_POSTGRES_DEFAULT_SCHEMA') }}"
      threads: 2
      port: "{{ env_var('LOCAL_ANALYTICS_POSTGRES_PORT') | int }}"
    prod:
      type: postgres
      host: "{{ env_var('PROD_ANALYTICS_POSTGRES_HOST') }}"
      user: "{{ env_var('PROD_ANALYTICS_POSTGRES_USER') }}"
      password: "{{ env_var('PROD_ANALYTICS_POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('PROD_ANALYTICS_POSTGRES_DB') }}"
      schema: "{{ env_var('PROD_ANALYTICS_POSTGRES_DEFAULT_SCHEMA') }}"
      threads: 2
      port: "{{ env_var('PROD_ANALYTICS_POSTGRES_PORT') | int }}"
