default:
  target: "{{ env_var('DBT_TARGET') }}"
  outputs:
    local:
      type: bigquery
      method: service-account
      project: "{{ env_var('LOCAL_ANALYTICS_GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('LOCAL_ANALYTICS_GCP_DEFAULT_DATASET') }}"
      threads: 4
      keyfile: "{{ env_var('LOCAL_GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: "{{ env_var('LOCAL_ANALYTICS_GCP_LOCATION') }}"
      priority: interactive
      timeout_seconds: 300
      retries: 1
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROD_ANALYTICS_GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('PROD_ANALYTICS_GCP_DEFAULT_DATASET') }}"
      threads: 4
      keyfile: "{{ env_var('PROD_GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: "{{ env_var('PROD_ANALYTICS_GCP_LOCATION') }}"
      priority: batch
      timeout_seconds: 3600
      retries: 3
